name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

permissions:
  contents: read
  packages: write

jobs:
  bridge:
    env:
      DOCKERFILE: src/Pavlok.Bridge/Dockerfile
      IMAGE_NAME: ghcr.io/silvenga/pavlok-net/bridge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
          version: latest

      - name: Detect Version
        run: |
          $ref = '${{ github.ref }}'
          if ($ref.StartsWith('refs/tags/'))
          {
              $version = ($ref -split '/' | Select-Object -Last 1)
          }
          else
          {
              $version = "0.0.1"
          }
          Write-Host "Detected version: '$version'."
          "BUILD_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      - uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') || github.actor != 'dependabot[bot]' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          file: ${{ env.DOCKERFILE }}
          context: .
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
          cache-from: ${{ github.actor != 'dependabot[bot]' && format('{0}:cache', env.IMAGE_NAME) || ''}}
          cache-to: ${{ github.actor != 'dependabot[bot]' && format('{0}:cache', env.IMAGE_NAME) || ''}}
          build-args: |
            BUILD_VERSION=${{ env.BUILD_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:v${{ env.BUILD_VERSION }}